# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GithubFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '4.0'
  pod 'RxCocoa', '4.0'
  pod 'Kingfisher', '4.0.1'
  pod 'ObjectMapper', '3.1'
  # Pods for GithubFeed

  target 'GithubFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
